# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TodaysCar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodaysCar
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'Moya/RxSwift', '~> 15.0'

  target 'TodaysCarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
